# Generated by Django 5.1 on 2024-08-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0002_documentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
    ]
